import { Inject, Injectable } from '@angular/core';
import { RestService } from '../../rest/rest.service';
import { UtilsService } from '../../utils/utils.service';
import { HttpClient } from '@angular/common/http';
import { MatDialog } from '@angular/material/dialog';
import { DOCUMENT } from '@angular/common';
import { environment } from 'src/environments/environment';
import { InfoComponent } from 'src/app/includes/utilities/popups/info/info.component';
import { BehaviorSubject } from 'rxjs';

@Injectable({
  providedIn: 'root'
})
export class GlobalDashboardService extends RestService {

  // Global Dashboard -- declarations
  public globalDashboardDataMaster!: any;
  public gotGlobalDashboardDataMaster$: BehaviorSubject<boolean> = new BehaviorSubject<boolean>(false);

  constructor(
    private utils: UtilsService,
    private _http: HttpClient,
    private _dialog: MatDialog,
    @Inject(DOCUMENT) private _document: any) {
    super(_http, _dialog);
  }

  // Get Global Dashboard -- Methods - starts
  getGobalDashboardData(selectedFinancialYear: any): void {
    if (environment.dummyData) {
      this.processGobalDashboardData({
        "success": 1,
        "message": "Data fetch from DB successful.",
        "result": {
          "SiteRiskAssessments": {
            "AssessmentsList": [
              {
                "SiteRiskAssessmentID": "4",
                "AssessmentName": "Kerala Branch Office-SRA-01",
                "AssessmentCode": "KBO1-SRA-01",
                "SiteID": "37",
                "ShortCode": "KBO1",
                "SiteName": "Kerala Branch Office",
                "StartDate": "Kerala Branch Office",
                "EndDate": "2024-03-28T00:00:00.000Z",
                "SiteRiskAssessmentStatusID": 2,
                "SiteRiskAssessmentStatus": "InProgress"
              },
              {
                "SiteRiskAssessmentID": "16",
                "AssessmentName": "Bihar Head Office-SRA-02",
                "AssessmentCode": "BHO-SRA-02",
                "SiteID": "20",
                "ShortCode": "BHO",
                "SiteName": "Bihar Head Office",
                "StartDate": "Bihar Head Office",
                "EndDate": "2024-03-31T00:00:00.000Z",
                "SiteRiskAssessmentStatusID": 3,
                "SiteRiskAssessmentStatus": "Published"
              },
              {
                "SiteRiskAssessmentID": "26",
                "AssessmentName": "Princesses Navya shree Mysore Head Office-SRA-01",
                "AssessmentCode": "MHO-SRA-01",
                "SiteID": "9",
                "ShortCode": "MHO",
                "SiteName": "Princesses Navya shree Mysore Head Office",
                "StartDate": "Princesses Navya shree Mysore Head Office",
                "EndDate": "2024-04-16T00:00:00.000Z",
                "SiteRiskAssessmentStatusID": 2,
                "SiteRiskAssessmentStatus": "InProgress"
              },
              {
                "SiteRiskAssessmentID": "36",
                "AssessmentName": "Ongole Head Office-SRA-01",
                "AssessmentCode": "OHO1-SRA-01",
                "SiteID": "30",
                "ShortCode": "OHO1",
                "SiteName": "Ongole Head Office",
                "StartDate": "Ongole Head Office",
                "EndDate": "2024-04-29T00:00:00.000Z",
                "SiteRiskAssessmentStatusID": 2,
                "SiteRiskAssessmentStatus": "InProgress"
              },
              {
                "SiteRiskAssessmentID": "49",
                "AssessmentName": "Mysore Office-SRA-01",
                "AssessmentCode": "MOF-SRA-01",
                "SiteID": "13",
                "ShortCode": "MOF",
                "SiteName": "Mysore Office",
                "StartDate": "Mysore Office",
                "EndDate": "2024-04-05T00:00:00.000Z",
                "SiteRiskAssessmentStatusID": 2,
                "SiteRiskAssessmentStatus": "InProgress"
              },
              {
                "SiteRiskAssessmentID": "59",
                "AssessmentName": "Site Head Office-SRA-01",
                "AssessmentCode": "SHO1-SRA-01",
                "SiteID": "31",
                "ShortCode": "SHO1",
                "SiteName": "Site Head Office",
                "StartDate": "Site Head Office",
                "EndDate": "2024-04-30T00:00:00.000Z",
                "SiteRiskAssessmentStatusID": 2,
                "SiteRiskAssessmentStatus": "InProgress"
              },
              {
                "SiteRiskAssessmentID": "67",
                "AssessmentName": "Haryana Sub Branch-SRA-03",
                "AssessmentCode": "HSB1-SRA-03",
                "SiteID": "32",
                "ShortCode": "HSB1",
                "SiteName": "Haryana Sub Branch",
                "StartDate": "Haryana Sub Branch",
                "EndDate": "2024-04-30T00:00:00.000Z",
                "SiteRiskAssessmentStatusID": 3,
                "SiteRiskAssessmentStatus": "Published"
              },
              {
                "SiteRiskAssessmentID": "78",
                "AssessmentName": "Bangaluru Branch office1-SRA-01",
                "AssessmentCode": "DHOO-SRA-01",
                "SiteID": "48",
                "ShortCode": "DHOO",
                "SiteName": "Bangaluru Branch office1",
                "StartDate": "Bangaluru Branch office1",
                "EndDate": "2024-04-30T00:00:00.000Z",
                "SiteRiskAssessmentStatusID": 2,
                "SiteRiskAssessmentStatus": "InProgress"
              },
              {
                "SiteRiskAssessmentID": "86",
                "AssessmentName": "Mysore branch office-SRA-03",
                "AssessmentCode": "MBO-SRA-03",
                "SiteID": "49",
                "ShortCode": "MBO",
                "SiteName": "Mysore branch office",
                "StartDate": "Mysore branch office",
                "EndDate": "2024-04-30T00:00:00.000Z",
                "SiteRiskAssessmentStatusID": 3,
                "SiteRiskAssessmentStatus": "Published"
              },
              {
                "SiteRiskAssessmentID": "99",
                "AssessmentName": "main branch SE-SRA-01",
                "AssessmentCode": "MBSE-SRA-01",
                "SiteID": "54",
                "ShortCode": "MBSE",
                "SiteName": "main branch SE",
                "StartDate": "main branch SE",
                "EndDate": "2024-04-30T00:00:00.000Z",
                "SiteRiskAssessmentStatusID": 2,
                "SiteRiskAssessmentStatus": "InProgress"
              },
              {
                "SiteRiskAssessmentID": "114",
                "AssessmentName": "Srikakulam Head Office-SRA-01",
                "AssessmentCode": "SHO2-SRA-01",
                "SiteID": "57",
                "ShortCode": "SHO2",
                "SiteName": "Srikakulam Head Office",
                "StartDate": "Srikakulam Head Office",
                "EndDate": "2024-04-30T00:00:00.000Z",
                "SiteRiskAssessmentStatusID": 3,
                "SiteRiskAssessmentStatus": "Published"
              },
              {
                "SiteRiskAssessmentID": "122",
                "AssessmentName": "Vadodara Main Office-SRA-02",
                "AssessmentCode": "VMNO-SRA-02",
                "SiteID": "58",
                "ShortCode": "VMNO",
                "SiteName": "Vadodara Main Office",
                "StartDate": "Vadodara Main Office",
                "EndDate": "2024-04-30T00:00:00.000Z",
                "SiteRiskAssessmentStatusID": 3,
                "SiteRiskAssessmentStatus": "Published"
              },
              {
                "SiteRiskAssessmentID": "130",
                "AssessmentName": "Bangalore head office Bangalore head office Bangalore head office Bangalore head officeBangalore head officeBangalore head officeBangalore head officeBangalore head officeBangalore head officeBangalore head office-SRA-02",
                "AssessmentCode": "BHOBHO-SRA-02",
                "SiteID": "51",
                "ShortCode": "BHOBHO",
                "SiteName": "Bangalore head office Bangalore head office Bangalore head office Bangalore head officeBangalore head officeBangalore head officeBangalore head officeBangalore head officeBangalore head officeBangalore head office",
                "StartDate": "Bangalore head office Bangalore head office Bangalore head office Bangalore head officeBangalore head officeBangalore head officeBangalore head officeBangalore head officeBangalore head officeBangalore head office",
                "EndDate": "2024-05-03T00:00:00.000Z",
                "SiteRiskAssessmentStatusID": 3,
                "SiteRiskAssessmentStatus": "Published"
              },
              {
                "SiteRiskAssessmentID": "5",
                "AssessmentName": "Riyadh Branch Office-SRA-01",
                "AssessmentCode": "RB-SRA-01",
                "SiteID": "2",
                "ShortCode": "RB",
                "SiteName": "Riyadh Branch Office",
                "StartDate": "Riyadh Branch Office",
                "EndDate": "2024-03-31T00:00:00.000Z",
                "SiteRiskAssessmentStatusID": 3,
                "SiteRiskAssessmentStatus": "Published"
              },
              {
                "SiteRiskAssessmentID": "17",
                "AssessmentName": "Gujarat Branch Office-SRA-01",
                "AssessmentCode": "GBO-SRA-01",
                "SiteID": "18",
                "ShortCode": "GBO",
                "SiteName": "Gujarat Branch Office",
                "StartDate": "Gujarat Branch Office",
                "EndDate": "2024-03-31T00:00:00.000Z",
                "SiteRiskAssessmentStatusID": 2,
                "SiteRiskAssessmentStatus": "InProgress"
              },
              {
                "SiteRiskAssessmentID": "27",
                "AssessmentName": "Maharashtra Head Office-SRA-02",
                "AssessmentCode": "MTHO-SRA-02",
                "SiteID": "14",
                "ShortCode": "MTHO",
                "SiteName": "Maharashtra Head Office",
                "StartDate": "Maharashtra Head Office",
                "EndDate": "2024-04-23T00:00:00.000Z",
                "SiteRiskAssessmentStatusID": 2,
                "SiteRiskAssessmentStatus": "InProgress"
              },
              {
                "SiteRiskAssessmentID": "37",
                "AssessmentName": "Site Test 2-SRA-01",
                "AssessmentCode": "ST2-SRA-01",
                "SiteID": "16",
                "ShortCode": "ST2",
                "SiteName": "Site Test 2",
                "StartDate": "Site Test 2",
                "EndDate": "2024-04-23T00:00:00.000Z",
                "SiteRiskAssessmentStatusID": 2,
                "SiteRiskAssessmentStatus": "InProgress"
              },
              {
                "SiteRiskAssessmentID": "51",
                "AssessmentName": "Belarus Branch Office-SRA-03",
                "AssessmentCode": "BLBO-SRA-03",
                "SiteID": "38",
                "ShortCode": "BLBO",
                "SiteName": "Belarus Branch Office",
                "StartDate": "Belarus Branch Office",
                "EndDate": "2024-04-30T00:00:00.000Z",
                "SiteRiskAssessmentStatusID": 3,
                "SiteRiskAssessmentStatus": "Published"
              },
              {
                "SiteRiskAssessmentID": "60",
                "AssessmentName": "Amlak Sub Head Office-SRA-01",
                "AssessmentCode": "ASHO2-SRA-01",
                "SiteID": "28",
                "ShortCode": "ASHO2",
                "SiteName": "Amlak Sub Head Office",
                "StartDate": "Amlak Sub Head Office",
                "EndDate": "2024-04-30T00:00:00.000Z",
                "SiteRiskAssessmentStatusID": 3,
                "SiteRiskAssessmentStatus": "Published"
              },
              {
                "SiteRiskAssessmentID": "68",
                "AssessmentName": "Haryana Sub Branch-SRA-04",
                "AssessmentCode": "HSB1-SRA-04",
                "SiteID": "32",
                "ShortCode": "HSB1",
                "SiteName": "Haryana Sub Branch",
                "StartDate": "Haryana Sub Branch",
                "EndDate": "2024-04-30T00:00:00.000Z",
                "SiteRiskAssessmentStatusID": 3,
                "SiteRiskAssessmentStatus": "Published"
              },
              {
                "SiteRiskAssessmentID": "79",
                "AssessmentName": "Mysore branch office-SRA-01",
                "AssessmentCode": "MBO-SRA-01",
                "SiteID": "49",
                "ShortCode": "MBO",
                "SiteName": "Mysore branch office",
                "StartDate": "Mysore branch office",
                "EndDate": "2024-04-29T00:00:00.000Z",
                "SiteRiskAssessmentStatusID": 3,
                "SiteRiskAssessmentStatus": "Published"
              },
              {
                "SiteRiskAssessmentID": "87",
                "AssessmentName": "Mysore branch office-SRA-04",
                "AssessmentCode": "MBO-SRA-04",
                "SiteID": "49",
                "ShortCode": "MBO",
                "SiteName": "Mysore branch office",
                "StartDate": "Mysore branch office",
                "EndDate": "2024-04-29T00:00:00.000Z",
                "SiteRiskAssessmentStatusID": 3,
                "SiteRiskAssessmentStatus": "Published"
              }
            ],
            "RisksList": [
              {
                "SiteID": "37",
                "ShortCode": "KBO1",
                "SiteName": "Kerala Branch Office",
                "SiteRiskAssessmentID": 60,
                "ScheduleRiskAssessmentID": 254,
                "ThreatRiskID": 20083,
                "StatusID": 7,
                "Status": "Publish Risk",
                "RiskTitle": "data crash",
                "Description": "data crash",
                "RiskCode": "2024-Q2-10",
                "ThreatCategoryID": 30,
                "ThreatCategory": "Software failure",
                "RiskOwnerID": "D20497F9-11F0-EE11-9F20-000C29AAA2A1",
                "RiskOwnerName": "devtest1  devtest1last",
                "IsCustomRisk": 0,
                "ControlEffectivenessID": 2,
                "ControlEffectiveness": "Medium",
                "RiskTreatmentStrategyID": 2,
                "RiskTreatmentStrategyName": "Tolerate",
                "OverallResidualRiskRatingID": 1,
                "OverallResidualRiskRating": "Low",
                "OverallInherentRiskRatingID": 2,
                "OverallInherentRiskRating": "Medium",
                "InherentLikelihoodRatingID": 3,
                "InherentLikelihoodRating": "High",
                "InherentImpactRatingID": 2,
                "InherentImpactRating": "Moderate",
                "ResidualLikelihoodRatingID": 3,
                "ResidualLikelihoodRating": "High",
                "ResidualImpactRatingID": 1,
                "ResidualImpactRating": "Minor",
                "ResidualRiskDescription": "",
                "RiskTolerateExplanation": "Testing tolerate",
                "RiskImpact": [
                  {
                    "ImpactID": 1,
                    "Impact": "Confidentiality",
                    "Code": "C"
                  }
                ]
              }
            ],
            "Top3Sites": [
              {
                "SiteID": "37",
                "ShortCode": "KBO1",
                "SiteName": "Kerala Branch Office",
                "ResudualRiskCount": 2
              },
              {
                "SiteID": "38",
                "ShortCode": "AHO",
                "SiteName": "AMLAK Head Office",
                "ResudualRiskCount": 2
              },
              {
                "SiteID": "40",
                "ShortCode": "KH01",
                "SiteName": "Kerala Head Office",
                "ResudualRiskCount": 2
              }
            ]
          },
          "RemediationTracker": [
            {
              "ActionItemID": "30155",
              "WorkflowRecordID": "30991",
              "ActionPlanTitle": "Sales register- BCMS",
              "ActionPlanDescription": "<p>Action Plan for&nbsp;<strong>sales register</strong></p>\n",
              "BCMModuleID": 8,
              "ActionItemModule": "BCMS Testing",
              "SourceActionPlanID": "47",
              "ActionItemSource": "Partial Simulation Test",
              "RiskDetails": "{ \"TestTitle\": \"Partial Simulation Test\", \"TestAssessmentID\": \"20046\" }",
              "SourceID": "20046",
              "ActionItemOwnerID": "D2ED8DC1-98C4-ED11-BB17-000C29A8F9E1",
              "ActionItemOwnerName": "mo_bank_18 Middle Name",
              "StartDate": "2024-06-19T00:00:00.000Z",
              "EndDate": "2024-06-27T00:00:00.000Z",
              "ActionItemStatusID": 2,
              "StatusName": "Assigned",
              "WorkflowStatusID": 1,
              "CriticalityID": "2",
              "CriticalityName": "Medium",
              "IsBudgetRequired": false,
              "BudgetedCost": null,
              "ProgressPercentage": null,
              "IsMarkCompleted": null,
              "IsExtentionRequested": null,
              "ExtendedTargetDate": null,
              "ExtentionExPlanation": null,
              "ExtentionRequestID": null,
              "ExtentionRequestStatusID": null,
              "ExtentionClosedDate": null,
              "IsEscalated": null,
              "EscalationRequestID": null,
              "EscalationRequestStatus": null,
              "EscalationExpiryDate": null,
              "IsCustomActionItem": true
            },
            {
              "ActionItemID": "30153",
              "WorkflowRecordID": "30978",
              "ActionPlanTitle": "PS- Compression",
              "ActionPlanDescription": null,
              "BCMModuleID": 8,
              "ActionItemModule": "BCMS Testing",
              "SourceActionPlanID": "44",
              "ActionItemSource": "Partial Simulation Test",
              "RiskDetails": "{ \"TestTitle\": \"Partial Simulation Test\", \"TestAssessmentID\": \"20046\" }",
              "SourceID": "20046",
              "ActionItemOwnerID": "30D1817D-8F8A-ED11-BAC5-000C29A8F9E1",
              "ActionItemOwnerName": "mo_bank_9 PT User 9",
              "StartDate": "2024-06-14T00:00:00.000Z",
              "EndDate": "2024-06-24T00:00:00.000Z",
              "ActionItemStatusID": 6,
              "StatusName": "Closed",
              "WorkflowStatusID": 5,
              "CriticalityID": "2",
              "CriticalityName": "Medium",
              "IsBudgetRequired": false,
              "BudgetedCost": null,
              "ProgressPercentage": "100",
              "IsMarkCompleted": true,
              "IsExtentionRequested": null,
              "ExtendedTargetDate": null,
              "ExtentionExPlanation": null,
              "ExtentionRequestID": null,
              "ExtentionRequestStatusID": null,
              "ExtentionClosedDate": null,
              "IsEscalated": null,
              "EscalationRequestID": null,
              "EscalationRequestStatus": null,
              "EscalationExpiryDate": null,
              "IsCustomActionItem": true
            },
            {
              "ActionItemID": "30154",
              "WorkflowRecordID": "30971",
              "ActionPlanTitle": "PS- Low pressure (high altitude)\n",
              "ActionPlanDescription": null,
              "BCMModuleID": 8,
              "ActionItemModule": "BCMS Testing",
              "SourceActionPlanID": "45",
              "ActionItemSource": "Partial Simulation Test",
              "RiskDetails": "{ \"TestTitle\": \"Partial Simulation Test\", \"TestAssessmentID\": \"20046\" }",
              "SourceID": "20046",
              "ActionItemOwnerID": "74B7F09A-758A-ED11-BAC5-000C29A8F9E1",
              "ActionItemOwnerName": "mo_bank_6 mid_name User 6",
              "StartDate": "2024-06-14T00:00:00.000Z",
              "EndDate": "2024-06-29T00:00:00.000Z",
              "ActionItemStatusID": 2,
              "StatusName": "Assigned",
              "WorkflowStatusID": 1,
              "CriticalityID": "1",
              "CriticalityName": "Low",
              "IsBudgetRequired": false,
              "BudgetedCost": null,
              "ProgressPercentage": null,
              "IsMarkCompleted": null,
              "IsExtentionRequested": null,
              "ExtendedTargetDate": null,
              "ExtentionExPlanation": null,
              "ExtentionRequestID": null,
              "ExtentionRequestStatusID": null,
              "ExtentionClosedDate": null,
              "IsEscalated": null,
              "EscalationRequestID": null,
              "EscalationRequestStatus": null,
              "EscalationExpiryDate": null,
              "IsCustomActionItem": true
            },
            {
              "ActionItemID": "30152",
              "WorkflowRecordID": "30967",
              "ActionPlanTitle": "PS- Vibration (as seen in truck and air transport)\n",
              "ActionPlanDescription": null,
              "BCMModuleID": 8,
              "ActionItemModule": "BCMS Testing",
              "SourceActionPlanID": "43",
              "ActionItemSource": "Partial Simulation Test",
              "RiskDetails": "{ \"TestTitle\": \"Partial Simulation Test\", \"TestAssessmentID\": \"20046\" }",
              "SourceID": "20046",
              "ActionItemOwnerID": "D2ED8DC1-98C4-ED11-BB17-000C29A8F9E1",
              "ActionItemOwnerName": "mo_bank_18 Middle Name",
              "StartDate": "2024-06-14T00:00:00.000Z",
              "EndDate": "2024-06-27T00:00:00.000Z",
              "ActionItemStatusID": 2,
              "StatusName": "Assigned",
              "WorkflowStatusID": 1,
              "CriticalityID": "2",
              "CriticalityName": "Medium",
              "IsBudgetRequired": false,
              "BudgetedCost": null,
              "ProgressPercentage": null,
              "IsMarkCompleted": null,
              "IsExtentionRequested": null,
              "ExtendedTargetDate": null,
              "ExtentionExPlanation": null,
              "ExtentionRequestID": null,
              "ExtentionRequestStatusID": null,
              "ExtentionClosedDate": null,
              "IsEscalated": null,
              "EscalationRequestID": null,
              "EscalationRequestStatus": null,
              "EscalationExpiryDate": null,
              "IsCustomActionItem": true
            },
            {
              "ActionItemID": "30151",
              "WorkflowRecordID": "30965",
              "ActionPlanTitle": "PS- Shock (from either manual or mechanical handling)",
              "ActionPlanDescription": "<p>test mobank 11 filling</p>\n",
              "BCMModuleID": 8,
              "ActionItemModule": "BCMS Testing",
              "SourceActionPlanID": "42",
              "ActionItemSource": "Partial Simulation Test",
              "RiskDetails": "{ \"TestTitle\": \"Partial Simulation Test\", \"TestAssessmentID\": \"20046\" }",
              "SourceID": "20046",
              "ActionItemOwnerID": "DE3A62E5-3B8B-ED11-BAC6-000C29A8F9E1",
              "ActionItemOwnerName": "mo_bank_11  ",
              "StartDate": "2024-06-14T00:00:00.000Z",
              "EndDate": "2024-06-19T00:00:00.000Z",
              "ActionItemStatusID": 2,
              "StatusName": "Assigned",
              "WorkflowStatusID": 1,
              "CriticalityID": "1",
              "CriticalityName": "Low",
              "IsBudgetRequired": true,
              "BudgetedCost": 20,
              "ProgressPercentage": null,
              "IsMarkCompleted": null,
              "IsExtentionRequested": null,
              "ExtendedTargetDate": null,
              "ExtentionExPlanation": null,
              "ExtentionRequestID": null,
              "ExtentionRequestStatusID": null,
              "ExtentionClosedDate": null,
              "IsEscalated": null,
              "EscalationRequestID": null,
              "EscalationRequestStatus": null,
              "EscalationExpiryDate": null,
              "IsCustomActionItem": true
            },
            {
              "ActionItemID": "30150",
              "WorkflowRecordID": "30961",
              "ActionPlanTitle": "PS- Temperature and relative humidity ",
              "ActionPlanDescription": "<p>ActionItem sourceTest</p>\n",
              "BCMModuleID": 8,
              "ActionItemModule": "BCMS Testing",
              "SourceActionPlanID": "41",
              "ActionItemSource": "Partial Simulation Test",
              "RiskDetails": "{ \"TestTitle\": \"Partial Simulation Test\", \"TestAssessmentID\": \"20046\" }",
              "SourceID": "20046",
              "ActionItemOwnerID": "6FB7F09A-758A-ED11-BAC5-000C29A8F9E1",
              "ActionItemOwnerName": "mo_bank_1  ",
              "StartDate": "2024-06-14T00:00:00.000Z",
              "EndDate": "2024-06-21T00:00:00.000Z",
              "ActionItemStatusID": 2,
              "StatusName": "Assigned",
              "WorkflowStatusID": 1,
              "CriticalityID": "2",
              "CriticalityName": "Medium",
              "IsBudgetRequired": true,
              "BudgetedCost": 1000,
              "ProgressPercentage": null,
              "IsMarkCompleted": null,
              "IsExtentionRequested": null,
              "ExtendedTargetDate": null,
              "ExtentionExPlanation": null,
              "ExtentionRequestID": null,
              "ExtentionRequestStatusID": null,
              "ExtentionClosedDate": null,
              "IsEscalated": null,
              "EscalationRequestID": null,
              "EscalationRequestStatus": null,
              "EscalationExpiryDate": null,
              "IsCustomActionItem": true
            },
            {
              "ActionItemID": "30149",
              "WorkflowRecordID": "30975",
              "ActionPlanTitle": "BCMS Source - Custom",
              "ActionPlanDescription": "<p>BCMS Source - Custom action paln</p>\n",
              "BCMModuleID": 8,
              "ActionItemModule": "BCMS Testing",
              "SourceActionPlanID": "40",
              "ActionItemSource": "BCMS New Test 1",
              "RiskDetails": "{ \"TestTitle\": \"BCMS New Test 1\", \"TestAssessmentID\": \"20028\" }",
              "SourceID": "20028",
              "ActionItemOwnerID": "6513981B-4714-EF11-9F4E-000C29AAA2A1",
              "ActionItemOwnerName": "devtest7  ",
              "StartDate": "2024-06-06T00:00:00.000Z",
              "EndDate": "2024-06-20T00:00:00.000Z",
              "ActionItemStatusID": 6,
              "StatusName": "Closed",
              "WorkflowStatusID": 5,
              "CriticalityID": "2",
              "CriticalityName": "Medium",
              "IsBudgetRequired": false,
              "BudgetedCost": null,
              "ProgressPercentage": "40",
              "IsMarkCompleted": true,
              "IsExtentionRequested": false,
              "ExtendedTargetDate": "2024-06-20T00:00:00.000Z",
              "ExtentionExPlanation": "request for extension",
              "ExtentionRequestID": "10106",
              "ExtentionRequestStatusID": 2,
              "ExtentionClosedDate": "2024-06-14T17:29:29.580Z",
              "IsEscalated": true,
              "EscalationRequestID": "27",
              "EscalationRequestStatus": "Escalation Approved",
              "EscalationExpiryDate": "2024-06-20T00:00:00.000Z",
              "IsCustomActionItem": true
            },
            {
              "ActionItemID": "30148",
              "WorkflowRecordID": "30951",
              "ActionPlanTitle": "Custom Action Items for BCMS Test Source",
              "ActionPlanDescription": "<p>Custom Action Items for BCMS Test Source action plan</p>\n",
              "BCMModuleID": 8,
              "ActionItemModule": "BCMS Testing",
              "SourceActionPlanID": "39",
              "ActionItemSource": "Test BCMS Demo -05 Jun",
              "RiskDetails": "{ \"TestTitle\": \"Test BCMS Demo -05 Jun\", \"TestAssessmentID\": \"20029\" }",
              "SourceID": "20029",
              "ActionItemOwnerID": "C36C2AB8-50D5-EE11-B0AA-000C296CF4F3",
              "ActionItemOwnerName": "Shwetha  ",
              "StartDate": "2024-06-06T00:00:00.000Z",
              "EndDate": "2024-06-12T00:00:00.000Z",
              "ActionItemStatusID": 4,
              "StatusName": "Claim-Closed",
              "WorkflowStatusID": 3,
              "CriticalityID": "2",
              "CriticalityName": "Medium",
              "IsBudgetRequired": false,
              "BudgetedCost": 0,
              "ProgressPercentage": "23",
              "IsMarkCompleted": false,
              "IsExtentionRequested": true,
              "ExtendedTargetDate": "2024-06-24T00:00:00.000Z",
              "ExtentionExPlanation": "requesting for extension",
              "ExtentionRequestID": "10104",
              "ExtentionRequestStatusID": 1,
              "ExtentionClosedDate": null,
              "IsEscalated": null,
              "EscalationRequestID": null,
              "EscalationRequestStatus": null,
              "EscalationExpiryDate": null,
              "IsCustomActionItem": true
            },
            {
              "ActionItemID": "30147",
              "WorkflowRecordID": "30928",
              "ActionPlanTitle": "Test RMT from Source BCMS",
              "ActionPlanDescription": null,
              "BCMModuleID": 8,
              "ActionItemModule": "BCMS Testing",
              "SourceActionPlanID": "38",
              "ActionItemSource": "Test BCMS BO and Observer",
              "RiskDetails": "{ \"TestTitle\": \"Test BCMS BO and Observer\", \"TestAssessmentID\": \"20041\" }",
              "SourceID": "20041",
              "ActionItemOwnerID": "C36C2AB8-50D5-EE11-B0AA-000C296CF4F3",
              "ActionItemOwnerName": "Shwetha  ",
              "StartDate": "2024-06-13T00:00:00.000Z",
              "EndDate": "2024-06-14T00:00:00.000Z",
              "ActionItemStatusID": 1,
              "StatusName": "New",
              "WorkflowStatusID": 1,
              "CriticalityID": null,
              "CriticalityName": null,
              "IsBudgetRequired": null,
              "BudgetedCost": null,
              "ProgressPercentage": null,
              "IsMarkCompleted": null,
              "IsExtentionRequested": null,
              "ExtendedTargetDate": null,
              "ExtentionExPlanation": null,
              "ExtentionRequestID": null,
              "ExtentionRequestStatusID": null,
              "ExtentionClosedDate": null,
              "IsEscalated": null,
              "EscalationRequestID": null,
              "EscalationRequestStatus": null,
              "EscalationExpiryDate": null,
              "IsCustomActionItem": false
            },
            {
              "ActionItemID": "30146",
              "WorkflowRecordID": null,
              "ActionPlanTitle": "TBBO- Action Item 1",
              "ActionPlanDescription": null,
              "BCMModuleID": 8,
              "ActionItemModule": "BCMS Testing",
              "SourceActionPlanID": "34",
              "ActionItemSource": "Test BCMS BO and Observer",
              "RiskDetails": "{ \"TestTitle\": \"Test BCMS BO and Observer\", \"TestAssessmentID\": \"20041\" }",
              "SourceID": "20041",
              "ActionItemOwnerID": "D20497F9-11F0-EE11-9F20-000C29AAA2A1",
              "ActionItemOwnerName": "devtest6  ",
              "StartDate": "2024-06-13T17:56:24.813Z",
              "EndDate": "2024-06-20T18:30:00.000Z",
              "ActionItemStatusID": 1,
              "StatusName": "New",
              "WorkflowStatusID": null,
              "CriticalityID": null,
              "CriticalityName": null,
              "IsBudgetRequired": null,
              "BudgetedCost": null,
              "ProgressPercentage": null,
              "IsMarkCompleted": null,
              "IsExtentionRequested": null,
              "ExtendedTargetDate": null,
              "ExtentionExPlanation": null,
              "ExtentionRequestID": null,
              "ExtentionRequestStatusID": null,
              "ExtentionClosedDate": null,
              "IsEscalated": null,
              "EscalationRequestID": null,
              "EscalationRequestStatus": null,
              "EscalationExpiryDate": null,
              "IsCustomActionItem": false
            },
            {
              "ActionItemID": "30145",
              "WorkflowRecordID": "30947",
              "ActionPlanTitle": "Test RMT from Source BCMS",
              "ActionPlanDescription": "<p>Test RMT from Source BCMS action plan description</p>\n",
              "BCMModuleID": 8,
              "ActionItemModule": "BCMS Testing",
              "SourceActionPlanID": "38",
              "ActionItemSource": "Test BCMS BO and Observer",
              "RiskDetails": "{ \"TestTitle\": \"Test BCMS BO and Observer\", \"TestAssessmentID\": \"20041\" }",
              "SourceID": "20041",
              "ActionItemOwnerID": "C36C2AB8-50D5-EE11-B0AA-000C296CF4F3",
              "ActionItemOwnerName": "Shwetha  ",
              "StartDate": "2024-06-13T00:00:00.000Z",
              "EndDate": "2024-06-19T00:00:00.000Z",
              "ActionItemStatusID": 6,
              "StatusName": "Closed",
              "WorkflowStatusID": 5,
              "CriticalityID": "2",
              "CriticalityName": "Medium",
              "IsBudgetRequired": true,
              "BudgetedCost": 1234,
              "ProgressPercentage": "99",
              "IsMarkCompleted": true,
              "IsExtentionRequested": true,
              "ExtendedTargetDate": "2024-06-19T00:00:00.000Z",
              "ExtentionExPlanation": "requesting for  extension",
              "ExtentionRequestID": "10103",
              "ExtentionRequestStatusID": 2,
              "ExtentionClosedDate": "2024-06-13T18:39:07.610Z",
              "IsEscalated": null,
              "EscalationRequestID": null,
              "EscalationRequestStatus": null,
              "EscalationExpiryDate": null,
              "IsCustomActionItem": true
            },
            {
              "ActionItemID": "30144",
              "WorkflowRecordID": null,
              "ActionPlanTitle": "TBBO- Action Item 1",
              "ActionPlanDescription": null,
              "BCMModuleID": 8,
              "ActionItemModule": "BCMS Testing",
              "SourceActionPlanID": "34",
              "ActionItemSource": "Test BCMS BO and Observer",
              "RiskDetails": "{ \"TestTitle\": \"Test BCMS BO and Observer\", \"TestAssessmentID\": \"20041\" }",
              "SourceID": "20041",
              "ActionItemOwnerID": "D20497F9-11F0-EE11-9F20-000C29AAA2A1",
              "ActionItemOwnerName": "devtest6  ",
              "StartDate": "2024-06-13T17:34:54.643Z",
              "EndDate": "2024-06-20T18:30:00.000Z",
              "ActionItemStatusID": 1,
              "StatusName": "New",
              "WorkflowStatusID": null,
              "CriticalityID": null,
              "CriticalityName": null,
              "IsBudgetRequired": null,
              "BudgetedCost": null,
              "ProgressPercentage": null,
              "IsMarkCompleted": null,
              "IsExtentionRequested": null,
              "ExtendedTargetDate": null,
              "ExtentionExPlanation": null,
              "ExtentionRequestID": null,
              "ExtentionRequestStatusID": null,
              "ExtentionClosedDate": null,
              "IsEscalated": null,
              "EscalationRequestID": null,
              "EscalationRequestStatus": null,
              "EscalationExpiryDate": null,
              "IsCustomActionItem": false
            },
            {
              "ActionItemID": "30143",
              "WorkflowRecordID": "30925",
              "ActionPlanTitle": "testing custom BCMS actionItem",
              "ActionPlanDescription": "<p>test</p>\n",
              "BCMModuleID": 8,
              "ActionItemModule": "BCMS Testing",
              "SourceActionPlanID": "37",
              "ActionItemSource": "Testing From DB Amlak_with new changes 1",
              "RiskDetails": "{ \"TestTitle\": \"Testing From DB Amlak_with new changes 1\", \"TestAssessmentID\": \"20044\" }",
              "SourceID": "20044",
              "ActionItemOwnerID": "433877BA-CCAA-EE11-B06E-000C296CF4F3",
              "ActionItemOwnerName": "Jami  Pavan",
              "StartDate": "2024-06-14T00:00:00.000Z",
              "EndDate": "2024-06-24T00:00:00.000Z",
              "ActionItemStatusID": 2,
              "StatusName": "Assigned",
              "WorkflowStatusID": 1,
              "CriticalityID": "3",
              "CriticalityName": "High",
              "IsBudgetRequired": true,
              "BudgetedCost": 20000,
              "ProgressPercentage": null,
              "IsMarkCompleted": null,
              "IsExtentionRequested": null,
              "ExtendedTargetDate": null,
              "ExtentionExPlanation": null,
              "ExtentionRequestID": null,
              "ExtentionRequestStatusID": null,
              "ExtentionClosedDate": null,
              "IsEscalated": null,
              "EscalationRequestID": null,
              "EscalationRequestStatus": null,
              "EscalationExpiryDate": null,
              "IsCustomActionItem": true
            },
            {
              "ActionItemID": "30142",
              "WorkflowRecordID": "30922",
              "ActionPlanTitle": "action item 1",
              "ActionPlanDescription": null,
              "BCMModuleID": 8,
              "ActionItemModule": "BCMS Testing",
              "SourceActionPlanID": "35",
              "ActionItemSource": "Testing From DB Amlak_with new changes 1",
              "RiskDetails": "{ \"TestTitle\": \"Testing From DB Amlak_with new changes 1\", \"TestAssessmentID\": \"20044\" }",
              "SourceID": "20044",
              "ActionItemOwnerID": "D20497F9-11F0-EE11-9F20-000C29AAA2A1",
              "ActionItemOwnerName": "devtest6  ",
              "StartDate": "2024-06-13T11:50:06.800Z",
              "EndDate": "2024-06-26T18:30:00.000Z",
              "ActionItemStatusID": 1,
              "StatusName": "New",
              "WorkflowStatusID": 1,
              "CriticalityID": null,
              "CriticalityName": null,
              "IsBudgetRequired": null,
              "BudgetedCost": null,
              "ProgressPercentage": null,
              "IsMarkCompleted": null,
              "IsExtentionRequested": null,
              "ExtendedTargetDate": null,
              "ExtentionExPlanation": null,
              "ExtentionRequestID": null,
              "ExtentionRequestStatusID": null,
              "ExtentionClosedDate": null,
              "IsEscalated": null,
              "EscalationRequestID": null,
              "EscalationRequestStatus": null,
              "EscalationExpiryDate": null,
              "IsCustomActionItem": false
            },
            {
              "ActionItemID": "30141",
              "WorkflowRecordID": "30921",
              "ActionPlanTitle": "Action ItemAMK-2191 Test - 3",
              "ActionPlanDescription": null,
              "BCMModuleID": 9,
              "ActionItemModule": "Crisis Management",
              "SourceActionPlanID": "2158",
              "ActionItemSource": null,
              "RiskDetails": "{ \"IncidentCode\": \"\", \"IncidentID\": \"\" }",
              "SourceID": "213",
              "ActionItemOwnerID": "30D1817D-8F8A-ED11-BAC5-000C29A8F9E1",
              "ActionItemOwnerName": "mo_bank_9 PT User 9",
              "StartDate": "2024-06-07T00:00:00.000Z",
              "EndDate": "2024-06-12T00:00:00.000Z",
              "ActionItemStatusID": 1,
              "StatusName": "New",
              "WorkflowStatusID": 1,
              "CriticalityID": null,
              "CriticalityName": null,
              "IsBudgetRequired": null,
              "BudgetedCost": null,
              "ProgressPercentage": null,
              "IsMarkCompleted": null,
              "IsExtentionRequested": null,
              "ExtendedTargetDate": null,
              "ExtentionExPlanation": null,
              "ExtentionRequestID": null,
              "ExtentionRequestStatusID": null,
              "ExtentionClosedDate": null,
              "IsEscalated": null,
              "EscalationRequestID": null,
              "EscalationRequestStatus": null,
              "EscalationExpiryDate": null,
              "IsCustomActionItem": false
            },
            {
              "ActionItemID": "30137",
              "WorkflowRecordID": null,
              "ActionPlanTitle": "this risk has to treated carefully",
              "ActionPlanDescription": null,
              "BCMModuleID": 9,
              "ActionItemModule": "Crisis Management",
              "SourceActionPlanID": "34",
              "ActionItemSource": null,
              "RiskDetails": "{ \"IncidentCode\": \"\", \"IncidentID\": \"\" }",
              "SourceID": "211",
              "ActionItemOwnerID": "2E8C222A-578B-ED11-BAC6-000C29A8F9E1",
              "ActionItemOwnerName": "devtest1  devtest1last",
              "StartDate": "2024-04-09T00:00:00.000Z",
              "EndDate": "2024-04-29T00:00:00.000Z",
              "ActionItemStatusID": 1,
              "StatusName": "New",
              "WorkflowStatusID": null,
              "CriticalityID": null,
              "CriticalityName": null,
              "IsBudgetRequired": null,
              "BudgetedCost": null,
              "ProgressPercentage": null,
              "IsMarkCompleted": null,
              "IsExtentionRequested": null,
              "ExtendedTargetDate": null,
              "ExtentionExPlanation": null,
              "ExtentionRequestID": null,
              "ExtentionRequestStatusID": null,
              "ExtentionClosedDate": null,
              "IsEscalated": null,
              "EscalationRequestID": null,
              "EscalationRequestStatus": null,
              "EscalationExpiryDate": null,
              "IsCustomActionItem": false
            },
            {
              "ActionItemID": "30138",
              "WorkflowRecordID": null,
              "ActionPlanTitle": "Test Action Item for Review Comment History",
              "ActionPlanDescription": null,
              "BCMModuleID": 9,
              "ActionItemModule": "Crisis Management",
              "SourceActionPlanID": "2124",
              "ActionItemSource": null,
              "RiskDetails": "{ \"IncidentCode\": \"\", \"IncidentID\": \"\" }",
              "SourceID": "211",
              "ActionItemOwnerID": "30D1817D-8F8A-ED11-BAC5-000C29A8F9E1",
              "ActionItemOwnerName": "mo_bank_9 PT User 9",
              "StartDate": "2024-05-30T00:00:00.000Z",
              "EndDate": "2024-06-06T00:00:00.000Z",
              "ActionItemStatusID": 1,
              "StatusName": "New",
              "WorkflowStatusID": null,
              "CriticalityID": null,
              "CriticalityName": null,
              "IsBudgetRequired": null,
              "BudgetedCost": null,
              "ProgressPercentage": null,
              "IsMarkCompleted": null,
              "IsExtentionRequested": null,
              "ExtendedTargetDate": null,
              "ExtentionExPlanation": null,
              "ExtentionRequestID": null,
              "ExtentionRequestStatusID": null,
              "ExtentionClosedDate": null,
              "IsEscalated": null,
              "EscalationRequestID": null,
              "EscalationRequestStatus": null,
              "EscalationExpiryDate": null,
              "IsCustomActionItem": false
            },
            {
              "ActionItemID": "30139",
              "WorkflowRecordID": null,
              "ActionPlanTitle": "Action Item AMK-2191 Test - 4",
              "ActionPlanDescription": null,
              "BCMModuleID": 9,
              "ActionItemModule": "Crisis Management",
              "SourceActionPlanID": "2159",
              "ActionItemSource": null,
              "RiskDetails": "{ \"IncidentCode\": \"\", \"IncidentID\": \"\" }",
              "SourceID": "211",
              "ActionItemOwnerID": "DE3A62E5-3B8B-ED11-BAC6-000C29A8F9E1",
              "ActionItemOwnerName": "mo_bank_11  ",
              "StartDate": "2024-06-10T00:00:00.000Z",
              "EndDate": "2024-06-18T00:00:00.000Z",
              "ActionItemStatusID": 1,
              "StatusName": "New",
              "WorkflowStatusID": null,
              "CriticalityID": null,
              "CriticalityName": null,
              "IsBudgetRequired": null,
              "BudgetedCost": null,
              "ProgressPercentage": null,
              "IsMarkCompleted": null,
              "IsExtentionRequested": null,
              "ExtendedTargetDate": null,
              "ExtentionExPlanation": null,
              "ExtentionRequestID": null,
              "ExtentionRequestStatusID": null,
              "ExtentionClosedDate": null,
              "IsEscalated": null,
              "EscalationRequestID": null,
              "EscalationRequestStatus": null,
              "EscalationExpiryDate": null,
              "IsCustomActionItem": false
            },
            {
              "ActionItemID": "30140",
              "WorkflowRecordID": null,
              "ActionPlanTitle": "this risk can also be treated",
              "ActionPlanDescription": null,
              "BCMModuleID": 9,
              "ActionItemModule": "Crisis Management",
              "SourceActionPlanID": "35",
              "ActionItemSource": null,
              "RiskDetails": "{ \"IncidentCode\": \"\", \"IncidentID\": \"\" }",
              "SourceID": "213",
              "ActionItemOwnerID": "433877BA-CCAA-EE11-B06E-000C296CF4F3",
              "ActionItemOwnerName": "Jami  Pavan",
              "StartDate": "2024-04-10T00:00:00.000Z",
              "EndDate": "2024-04-29T00:00:00.000Z",
              "ActionItemStatusID": 1,
              "StatusName": "New",
              "WorkflowStatusID": null,
              "CriticalityID": null,
              "CriticalityName": null,
              "IsBudgetRequired": null,
              "BudgetedCost": null,
              "ProgressPercentage": null,
              "IsMarkCompleted": null,
              "IsExtentionRequested": null,
              "ExtendedTargetDate": null,
              "ExtentionExPlanation": null,
              "ExtentionRequestID": null,
              "ExtentionRequestStatusID": null,
              "ExtentionClosedDate": null,
              "IsEscalated": null,
              "EscalationRequestID": null,
              "EscalationRequestStatus": null,
              "EscalationExpiryDate": null,
              "IsCustomActionItem": false
            },
          ],
          "DashboardsList": [
            {
              "DashboardID": 1,
              "DashboardName": "GlobalDashboard",
              "DashboardWidgets": [
                {
                  "WidgetID": 1,
                  "WidgetName": "Site Risks"
                },
                {
                  "WidgetID": 2,
                  "WidgetName": "Remediation Tracker"
                }
              ]
            }
          ],
          "FinancialYearsList": [
            {
              "ID": 1,
              "Year": 2022
            },
            {
              "ID": 2,
              "Year": 2023
            },
            {
              "ID": 3,
              "Year": 2024
            },
            {
              "ID": 4,
              "Year": 2025
            },
            {
              "ID": 5,
              "Year": 2026
            }
          ]
        },
        "error": {
          "errorCode": null,
          "errorMessage": null
        }
      });
    }
    else {
      let data = {
        selectedYears: selectedFinancialYear? (selectedFinancialYear).toString() : null
      }
      this.post("/business-continuity-management/dashboard/get-global-dashboard-data", { "data": data }).subscribe(res => {
        next:
        if (res.success == 1) {
          this.processGobalDashboardData(res)
        } else {
          if (res.error.errorCode && res.error.errorCode == "TOKEN_EXPIRED")
            this.utils.relogin(this._document);
          else
            this.popupInfo("Unsuccessful", res.error.errorMessage)
        }
      });
    }
  }

  processGobalDashboardData(response: any): void {
    this.globalDashboardDataMaster = response.result;
    this.gotGlobalDashboardDataMaster$.next(true);
  }
  // Get Global Dashboard -- Methods - ends

  // Common Methods
  popupInfo(title: string, message: string) {
    const timeout = 3000; // 3 seconds
    const confirm = this._dialog.open(InfoComponent, {
      disableClose: true,
      minWidth: "300px",
      panelClass: "dark",
      data: {
        title: title,
        content: message
      }
    });

    confirm.afterOpened().subscribe(result => {
      setTimeout(() => {
        confirm.close();
      }, timeout)
    });
  }
}
